#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Keitaro Nakamaura
# SPDX-License-Identifier: BSD-3-Clause

import sys

num = 0
for line in sys.stdin:
    try:
        print('%s+' % line.strip(),end='')
        num += int(line)
    except:
        print('%s+' % line.strip(),end='')
        num += float(line)

print("\033[1D\033[K",'=',num)
