#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Keitaro Nakamaura
# SPDX-License-Identifier: BSD-3-Clause

import sys

num = 0
for line in sys.stdin:
    try:
        num += int(line)
    except:
        num += float(line)

print(num)
